// AUTO-GENERATED from Province snapshot info.xlsx. Do not edit by hand.
// Run: node scripts/generateSnapshotFields.js

import type { SnapshotField } from './snapshotModel';

export const SNAPSHOT_FIELDS: SnapshotField[] = [
  {
    key: "provinceName",
    label: "Province Name",
    section: "throne",
    rawSource: "IS Export \"Name\"",
  },
  {
    key: "rulerName",
    label: "Ruler Name",
    section: "throne",
    rawSource: "IS Export \"Ruler\"",
  },
  {
    key: "kd",
    label: "KD",
    section: "throne",
    rawSource: "IS Export \"Location\"",
  },
  {
    key: "race",
    label: "Race",
    section: "throne",
    rawSource: "IS Export \"Race\" , Manual input",
  },
  {
    key: "personality",
    label: "Personality",
    section: "throne",
    rawSource: "IS Export \"Personality\" , Manual input",
  },
  {
    key: "land",
    label: "Land",
    section: "throne",
    rawSource: "IS Export \"Acres\" , Manual input",
  },
  {
    key: "honor",
    label: "Honor",
    section: "throne",
    rawSource: "IS Export \"Honor\", manual input",
  },
  {
    key: "peasants",
    label: "Peasants",
    section: "throne",
    rawSource: "IS Export \"Peons\", Manual input",
  },
  {
    key: "buildingEfficiency",
    label: "Building Efficiency",
    section: "throne",
    rawSource: "IS Export \"BE\" , Manual input , Calculated",
  },
  {
    key: "money",
    label: "Money",
    section: "throne",
    rawSource: "IS Export \"GCs\" , Manual input",
  },
  {
    key: "food",
    label: "Food",
    section: "throne",
    rawSource: "IS Export \"Food\" , Manual input",
  },
  {
    key: "runes",
    label: "Runes",
    section: "throne",
    rawSource: "IS Export \"Runes\" , Manual input",
  },
  {
    key: "tradeBalance",
    label: "Trade Balance",
    section: "throne",
    rawSource: "IS Export \"TB\"",
  },
  {
    key: "networth",
    label: "Networth",
    section: "throne",
    rawSource: "IS Export \"NW\" , Manual input , calculated",
  },
  {
    key: "soldiers",
    label: "Soldiers",
    section: "throne",
    rawSource: "IS Export \"Solds\", Manual input",
  },
  {
    key: "offspecs",
    label: "OffSpecs",
    section: "throne",
    rawSource: "IS Export \"OS\" , Manual input",
  },
  {
    key: "defspecs",
    label: "DefSpecs",
    section: "throne",
    rawSource: "IS Export \"DS\" , Manual input",
  },
  {
    key: "elites",
    label: "Elites",
    section: "throne",
    rawSource: "IS Export \"Leets\" , Manual input",
  },
  {
    key: "thieves",
    label: "Thieves",
    section: "throne",
    rawSource: "IS Export \"Thv\" , manual input",
  },
  {
    key: "wizards",
    label: "Wizards",
    section: "throne",
    rawSource: "IS Export \"Wiz\", manual input",
  },
  {
    key: "horses",
    label: "horses",
    section: "throne",
    rawSource: "IS Export \"Horses\", manual input",
  },
  {
    key: "prisoners",
    label: "Prisoners",
    section: "throne",
    rawSource: "IS Export \" Prisoners\", manual input",
  },
  {
    key: "offensivePoints",
    label: "Offensive Points",
    section: "throne",
    rawSource: "IS Export \"Off\" , calculated",
  },
  {
    key: "defensizePoints",
    label: "Defensize Points",
    section: "throne",
    rawSource: "IS Export \"Def\", calculated",
  },
  {
    key: "activeSpells",
    label: "Active Spells",
    section: "throne",
    rawSource: "IS Export \"GoodSpells\" + \"BadSpells\", manual input",
  },
  {
    key: "peasants",
    label: "Peasants",
    section: "population",
    rawSource: "IS Export \"Peons\" , manual input",
  },
  {
    key: "army",
    label: "Army",
    section: "population",
    rawSource: "calculated",
  },
  {
    key: "thieves",
    label: "Thieves",
    section: "population",
    rawSource: "IS Export \"Thv\", manual input",
  },
  {
    key: "wizards",
    label: "Wizards",
    section: "population",
    rawSource: "IS Export \"Wiz\" , Manual input",
  },
  {
    key: "total",
    label: "Total",
    section: "population",
    rawSource: "calculated",
  },
  {
    key: "maxPopulation",
    label: "Max Population",
    section: "population",
    rawSource: "calculated",
  },
  {
    key: "peasants",
    label: "Peasants",
    section: "economy",
    rawSource: "IS Export \"Peons\" , manual input",
  },
  {
    key: "unemployedPeasants",
    label: "Unemployed Peasants",
    section: "economy",
    rawSource: "calculated",
  },
  {
    key: "unfilledJobs",
    label: "Unfilled Jobs",
    section: "economy",
    rawSource: "calculated",
  },
  {
    key: "employmentPercent",
    label: "Employment %",
    section: "economy",
    rawSource: "calculated",
  },
  {
    key: "dailyIncome",
    label: "Daily Income",
    section: "economy",
    rawSource: "Calculated",
  },
  {
    key: "dailyWages",
    label: "Daily Wages",
    section: "economy",
    rawSource: "Calculated",
  },
  {
    key: "income",
    label: "Income",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "wages",
    label: "Wages",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "draftCosts",
    label: "Draft Costs",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "netGc",
    label: "Net gc",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "newPeasantsTick",
    label: "new Peasants/tick",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "foodGrown",
    label: "Food Grown",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "foodNeeded",
    label: "Food Needed",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "foodDecayed",
    label: "Food Decayed",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "netFood",
    label: "Net Food",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "runesProduced",
    label: "Runes produced",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "runesDecayed",
    label: "Runes Decayed",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "netRunes",
    label: "Net Runes",
    section: "netChanges",
    rawSource: "Calculated",
  },
  {
    key: "baseMilitaryEfficiency",
    label: "Base Military efficiency",
    section: "military",
    rawSource: "Calculated",
  },
  {
    key: "offensiveMilitaryEfficiency",
    label: "Offensive Military Efficiency",
    section: "military",
    rawSource: "IS Export \"OME\" , calculated",
  },
  {
    key: "defensiveMilitaryEfficiency",
    label: "Defensive Military Efficiency",
    section: "military",
    rawSource: "IS Export \"DME\" , calculated",
  },
  {
    key: "netOffensivePointsAtHome",
    label: "Net Offensive Points at Home",
    section: "military",
    rawSource: "IS Export \"OffHome\"",
  },
  {
    key: "netDefensivePointsAtHome",
    label: "Net Defensive Points at Home",
    section: "military",
    rawSource: "IS Export \"DefHome\"",
  },
  {
    key: "totalPopulation",
    label: "Total Population",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "peasants",
    label: "Peasants",
    section: "military",
    rawSource: "IS Export \"Peons\" , manual input",
  },
  {
    key: "wizards",
    label: "Wizards",
    section: "military",
    rawSource: "IS Export \"Wiz\" , manual input",
  },
  {
    key: "militaryThiefPopulation",
    label: "Military & Thief Population",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "soldiers",
    label: "Soldiers",
    section: "military",
    rawSource: "IS Export \"Solds\" , manual input",
  },
  {
    key: "freeSpecialistCreditsLeft",
    label: "Free Specialist Credits Left",
    section: "military",
    rawSource: "IS Export \"T-credits\" , manual input",
  },
  {
    key: "draftRate",
    label: "Draft Rate",
    section: "military",
    rawSource: "IS Export \"DrftRate\" , manual input",
  },
  {
    key: "draftTarget",
    label: "Draft Target",
    section: "military",
    rawSource: "IS Export \"DrftTgt\" , manaul input",
  },
  {
    key: "wageRate",
    label: "Wage Rate",
    section: "military",
    rawSource: "IS Export \"Wages\", manual input",
  },
  {
    key: "offspecOffDef",
    label: "OffSpec Off/Def",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "offspecOwned",
    label: "OffSpec Owned",
    section: "military",
    rawSource: "IS Export \"OS\" , manual input",
  },
  {
    key: "offspecTraining",
    label: "OffSpec Training",
    section: "military",
    rawSource: "IS Export \"OS Train\" , manual input",
  },
  {
    key: "offspecCost",
    label: "OffSpec Cost",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "offspecMaxAbleToTrain",
    label: "OffSpec max able to train",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "defspecOffDef",
    label: "DefSpec Off/Def",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "defspecOwned",
    label: "DefSpec Owned",
    section: "military",
    rawSource: "IS Export \"DS\" , manual input",
  },
  {
    key: "defspecTraining",
    label: "DefSpec Training",
    section: "military",
    rawSource: "IS Export \"DS Train\" , manual input",
  },
  {
    key: "defspecCost",
    label: "DefSpec Cost",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "defspecMaxAbleToTrain",
    label: "DefSpec max able to train",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "eliteOffDef",
    label: "Elite Off/Def",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "eliteOwned",
    label: "Elite Owned",
    section: "military",
    rawSource: "IS Export \"Leets\" , manual input",
  },
  {
    key: "eliteTraining",
    label: "Elite Training",
    section: "military",
    rawSource: "IS Export \"Elite Train\" , manual input",
  },
  {
    key: "eliteCost",
    label: "Elite Cost",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "eliteMaxAbleToTrain",
    label: "Elite Max able to train",
    section: "military",
    rawSource: "Calculated",
  },
  {
    key: "thiefOwned",
    label: "Thief Owned",
    section: "military",
    rawSource: "IS Export \"Thv\" , manual input",
  },
  {
    key: "thiefTraining",
    label: "Thief Training",
    section: "military",
    rawSource: "IS Export \"Thief Train\" , manual input",
  },
  {
    key: "thiefCost",
    label: "Thief Cost",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "thiefMaxAbleToTrain",
    label: "Thief Max able to train",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "baseTrainingSpeed",
    label: "Base training Speed",
    section: "military",
    rawSource: "calculated",
  },
  {
    key: "availableWorkers",
    label: "Available Workers",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "availableJobs",
    label: "Available Jobs",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "buildingEfficiency",
    label: "Building Efficiency",
    section: "buildingsGrowth",
    rawSource: "IS Export \"BE\" , manual input, calculated",
  },
  {
    key: "workersNeededForMaxEfficiency",
    label: "Workers Needed for Max efficiency",
    section: "buildingsGrowth",
    rawSource: "Calculated",
  },
  {
    key: "totalLand",
    label: "Total Land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Acres\" , manual input",
  },
  {
    key: "totalUndevelopedLand",
    label: "Total undeveloped Land",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "constructionTime",
    label: "Construction Time",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "freeBuildingCredits",
    label: "Free building credits",
    section: "buildingsGrowth",
    rawSource: "IS Export \"B-Credits\" , manual input",
  },
  {
    key: "constructionCost",
    label: "Construction Cost",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "maxBuildableNow",
    label: "Max buildable now",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "razeCost",
    label: "Raze Cost",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "maximumRazeableNow",
    label: "Maximum Razeable now",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "barrenLandQty",
    label: "Barren Land qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "barrenLandPercentOfTotalLand",
    label: "Barren Land % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Barr\" , manual input",
  },
  {
    key: "barrenLandCurrentEffects",
    label: "Barren Land current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "homesQty",
    label: "Homes Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "homesPercentOfTotalLand",
    label: "Homes % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Home\" , manual input",
  },
  {
    key: "homesCurrentEffects",
    label: "Homes current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "homesInProgress",
    label: "Homes in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "farmsQty",
    label: "Farms Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "farmsPercentOfTotalLand",
    label: "Farms % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Farm\" , manual input",
  },
  {
    key: "farmsCurrentEffects",
    label: "Farms current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "farmsInProgress",
    label: "Farms in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "millsQty",
    label: "Mills Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "millsPercentOfTotalLand",
    label: "Mills % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Mill\" , manual input",
  },
  {
    key: "millsCurrentEffects",
    label: "Mills current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "millsInProgress",
    label: "Mills in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "banksQty",
    label: "Banks Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "banksPercentOfTotalLand",
    label: "Banks % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Bank\" , manual input",
  },
  {
    key: "banksCurrentEffects",
    label: "Banks current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "banksInProgress",
    label: "Banks in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "trainingGroundsQty",
    label: "Training Grounds Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "trainingGroundsPercentOfTotalLand",
    label: "Training Grounds % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"TGs\" , manual input",
  },
  {
    key: "trainingGroundsCurrentEffects",
    label: "Training Grounds current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "trainingGroundsInProgress",
    label: "Training Grounds in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "armouriesQty",
    label: "Armouries Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "armouriesPercentOfTotalLand",
    label: "Armouries % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Arms\" , manual input",
  },
  {
    key: "armouriesCurrentEffects",
    label: "Armouries current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "armouriesInProgress",
    label: "Armouries in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "barracksQty",
    label: "Barracks Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "barracksPercentOfTotalLand",
    label: "Barracks % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Rax\" , manual input",
  },
  {
    key: "barracksCurrentEffects",
    label: "Barracks current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "barracksInProgress",
    label: "Barracks in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "fortsQty",
    label: "Forts Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "fortsPercentOfTotalLand",
    label: "Forts % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Fort\" , manual input",
  },
  {
    key: "fortsCurrentEffects",
    label: "Forts current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "fortsInProgress",
    label: "Forts in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "castlesQty",
    label: "Castles Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "castlesPercentOfTotalLand",
    label: "Castles % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Cast\" , manual input",
  },
  {
    key: "castlesCurrentEffects",
    label: "Castles current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "castlesInProgress",
    label: "Castles in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "hospitalsQty",
    label: "Hospitals Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "hospitalsPercentOfTotalLand",
    label: "Hospitals % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Hosp\" , manual input",
  },
  {
    key: "hospitalsCurrentEffects",
    label: "Hospitals current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "hospitalsInProgress",
    label: "Hospitals in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "guildsQty",
    label: "Guilds Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "guildsPercentOfTotalLand",
    label: "Guilds % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Guil\" , manual input",
  },
  {
    key: "guildsCurrentEffects",
    label: "Guilds current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "guildsInProgress",
    label: "Guilds in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "towersQty",
    label: "Towers Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "towersPercentOfTotalLand",
    label: "Towers % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Towe\" , manual input",
  },
  {
    key: "towersCurrentEffects",
    label: "Towers current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "towersInProgress",
    label: "Towers in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "thievesDensQty",
    label: "Thieves' Dens Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "thievesDensPercentOfTotalLand",
    label: "Thieves' Dens % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"TDs\" , manual input",
  },
  {
    key: "thievesDensCurrentEffects",
    label: "Thieves' Dens current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "thievesDensInProgress",
    label: "Thieves' Dens in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "watchTowersQty",
    label: "Watch Towers Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "watchTowersPercentOfTotalLand",
    label: "Watch Towers % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"WTs\" , manual input",
  },
  {
    key: "watchTowersCurrentEffects",
    label: "Watch Towers current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "watchTowersInProgress",
    label: "Watch Towers in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "universitiesQty",
    label: "Universities Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "universitiesPercentOfTotalLand",
    label: "Universities % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Univ\" , manual input",
  },
  {
    key: "universitiesCurrentEffects",
    label: "Universities current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "universitiesInProgress",
    label: "Universities in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "librariesQty",
    label: "Libraries Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "librariesPercentOfTotalLand",
    label: "Libraries % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Libs\" , manual input",
  },
  {
    key: "librariesCurrentEffects",
    label: "Libraries current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "librariesInProgress",
    label: "Libraries in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "stablesQty",
    label: "Stables Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "stablesPercentOfTotalLand",
    label: "Stables % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Stab\" , manual input",
  },
  {
    key: "stablesCurrentEffects",
    label: "Stables current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "stablesInProgress",
    label: "Stables in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "dungeonsQty",
    label: "Dungeons Qty",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "dungeonsPercentOfTotalLand",
    label: "Dungeons % of total land",
    section: "buildingsGrowth",
    rawSource: "IS Export \"Dung\" , manual input",
  },
  {
    key: "dungeonsCurrentEffects",
    label: "Dungeons current effects",
    section: "buildingsGrowth",
    rawSource: "calculated",
  },
  {
    key: "dungeonsInProgress",
    label: "Dungeons in progress",
    section: "buildingsGrowth",
    rawSource: "manual input",
  },
  {
    key: "alchemyOfBooks",
    label: "Alchemy # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "alchemyEffect",
    label: "Alchemy Effect",
    section: "science",
    rawSource: "IS Export \"Alche\" , manual input",
  },
  {
    key: "toolsOfBooks",
    label: "Tools # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "toolsEffect",
    label: "Tools Effect",
    section: "science",
    rawSource: "IS Export \"Tools\" , manual input",
  },
  {
    key: "housingOfBooks",
    label: "Housing # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "housingEffect",
    label: "Housing Effect",
    section: "science",
    rawSource: "IS Export \"Housi\" , manual input",
  },
  {
    key: "productionOfBooks",
    label: "Production # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "productionEffect",
    label: "Production Effect",
    section: "science",
    rawSource: "IS Export \"Produ\" , manual input",
  },
  {
    key: "bookkeepingOfBooks",
    label: "Bookkeeping # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "bookkeepingEffect",
    label: "Bookkeeping Effect",
    section: "science",
    rawSource: "IS Export \"Bookk\" , manual input",
  },
  {
    key: "artisanOfBooks",
    label: "Artisan # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "artisanEffect",
    label: "Artisan Effect",
    section: "science",
    rawSource: "IS Export \"Artis\" , manual input",
  },
  {
    key: "strategyOfBooks",
    label: "Strategy # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "strategyEffect",
    label: "Strategy Effect",
    section: "science",
    rawSource: "IS Export \"Strat\" , manual input",
  },
  {
    key: "siegeOfBooks",
    label: "Siege # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "siegeEffect",
    label: "Siege Effect",
    section: "science",
    rawSource: "IS Export \"Siege\" , manual input",
  },
  {
    key: "tacticsOfBooks",
    label: "Tactics # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "tacticsEffect",
    label: "Tactics Effect",
    section: "science",
    rawSource: "IS Export \"Tacti\" , manual input",
  },
  {
    key: "valorOfBooks",
    label: "Valor # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "valorEffect",
    label: "Valor Effect",
    section: "science",
    rawSource: "IS Export \"Valor\" , manual input",
  },
  {
    key: "heroismOfBooks",
    label: "Heroism # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "heroismEffect",
    label: "Heroism Effect",
    section: "science",
    rawSource: "IS Export \"Heroi\" , manual input",
  },
  {
    key: "resilienceOfBooks",
    label: "Resilience # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "resilienceEffect",
    label: "Resilience Effect",
    section: "science",
    rawSource: "IS Export \"Resil\" , manual input",
  },
  {
    key: "crimeOfBooks",
    label: "Crime # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "crimeEffect",
    label: "Crime Effect",
    section: "science",
    rawSource: "IS Export \"Crime\" , manual input",
  },
  {
    key: "channelingOfBooks",
    label: "Channeling # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "channelingEffect",
    label: "Channeling Effect",
    section: "science",
    rawSource: "IS Export \"Chann\" , manual input",
  },
  {
    key: "shieldingOfBooks",
    label: "Shielding # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "shieldingEffect",
    label: "Shielding Effect",
    section: "science",
    rawSource: "IS Export \"Shiel\" , manual input",
  },
  {
    key: "cunningOfBooks",
    label: "Cunning # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "cunningEffect",
    label: "Cunning Effect",
    section: "science",
    rawSource: "IS Export \"Cunni\" , manual input",
  },
  {
    key: "sorceryOfBooks",
    label: "Sorcery # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "sorceryEffect",
    label: "Sorcery Effect",
    section: "science",
    rawSource: "IS Export \"Sorce\" , manual input",
  },
  {
    key: "finesseOfBooks",
    label: "Finesse # of books",
    section: "science",
    rawSource: "calculated, manual input",
  },
  {
    key: "finesseEffect",
    label: "Finesse Effect",
    section: "science",
    rawSource: "IS Export \"Fines\" , manual input",
  },
];
